### ISSUE TITLE
Feature Request: Radio Button Group

### ISSUE THREAD

**Issue by defuncart** [ubuntu/yaru_widgets.dart#103]
Once again thank you for creating this package :)

Are Radio Buttons planned? I'm not a regular ubuntu user, however AFAIK radio buttons are part of yaru design.

**Comment by defuncart** [comment]
I saw that [ToggleButtons](https://api.flutter.dev/flutter/material/ToggleButtons-class.html)s are used in `YaruToggleButtonsRow`, however what I mean is a radio button:

![image](https://user-images.githubusercontent.com/13286425/155551915-274959b4-6835-433c-8ffc-3f89a401e1bb.png)

Are radio buttons part of Yaru's design? If not, what UI element would be used in their place, a toggle button?

**Comment by Feichtmeier** [comment]
There is a RadioListTile in material.dart

**Comment by defuncart** [comment]
I'm closing this issue as after looking at https://github.com/canonical/ubuntu-desktop-installer and using https://github.com/malisipi/ubuntu-tour, it doesn't seem that radio buttons are part of Yaru's design language. I also cannot find any recent and relevant info online. `YaruToggleButtonsRow` satisfies my needs :)
