### ISSUE TITLE
Change the content padding of the `YaruAlertDialog`

### ISSUE THREAD

**Issue by GroovinChip** [ubuntu/yaru_widgets.dart#104]
Currently, the `contentPadding` property of the `AlertDialog` that is build by the `YaruAlertDialog` widget is set to `EdgeInsets.zero`. This results in dialogs with content that run right up to the left and right edges, as seen in the screenshot below.

It would be great if you guys could update this property with some default padding. Alternatively, you could expose this property for developers to set themselves.

![Screen Shot 2022-03-01 at 10 47 03 AM](https://user-images.githubusercontent.com/4250470/156200985-552f9af2-abc8-4226-97db-38de6ab47d8e.png)

**Comment by Jupi007** [comment]
@GroovinChip did #107 fixed your problem?

**Comment by GroovinChip** [comment]
I haven’t used the package since I filed this issue as my requirements changed shortly afterwards. I’m going to assume it does fix the problem.

**Comment by Jupi007** [comment]
Okay, thanks :)
