### ISSUE TITLE
YaruPageItem title creates new lines

### ISSUE THREAD

**Issue by Jupi007** [ubuntu/yaru_widgets.dart#174]
When becoming too long, the `YaruPageItem` wrap the title text into a new line, which isn't looking good:

![Capture d’écran du 2022-08-07 17-29-18](https://user-images.githubusercontent.com/36476595/183298964-fc8243c6-86db-4f06-842a-4a16b93e71b4.png)

A potential "fix" for apps could be to set the exactly needed sidebar width, but with internationalization it is not possible to deal with so much line size.
IMO the best solution is to ellipse the text like in nautilus:

![Capture d’écran du 2022-08-07 17-36-43](https://user-images.githubusercontent.com/36476595/183298962-1a71b943-9080-427d-b4f5-1afdb39c8744.png)

As the title is not a `string` but a free widget, I propose to locally change the `max-line` to `1` and the `overflow` to `TextOverflow.ellipsis`, with something like a `YaruPageItemTitle` widget, so this is optional.

**Comment by Feichtmeier** [comment]
Good change, I actually wanted to push the ellipses for the tiles but I have forgotten :D
