### ISSUE TITLE
src becomes messy

### ISSUE THREAD

**Issue by Jupi007** [ubuntu/yaru_widgets.dart#180]
The `/src` folder is becoming a bit messy with 37 class files.
I think it would be nice to organize all those into subfolder (layout, controls, dialog, ...).

I don't think it would break something in apps, as we rely on a root `yaru_widgets.dart` index file which export all files, but maybe I'm wrong.

Wdyt @Feichtmeier ?

**Comment by Feichtmeier** [comment]
nice idea - if this does not clash with some "common dart style" stuff? go for it

**Comment by Jupi007** [comment]
Well, I already saw many widget libraries which was sort their files into subfolder :)

**Comment by Jupi007** [comment]
Here is a proposal new organization of widgets files:

*/dialog*

- `yaru_alert_dialog.dart`
- `yaru_dialog_title.dart`
- `yaru_simple_dialog.dart`

*/utility*

- `yaru_banner.dart`
- `yaru_carousel.dart`
- `yaru_draggable.dart`
- `yaru_expandable.dart`
- `yaru_expansion_panel_list.dart`
- `yaru_safe_image.dart`
- `yaru_selectable_container.dart`
- `yaru_search_app_bar.dart`
- `ubuntu_logo.dart`

*/control*

- `yaru_color_disk.dart`
- `yaru_color_picker_button.dart`
- `yaru_option_button.dart`
- `yaru_round_icon_button.dart`
- `yaru_round_toggle_button.dart`
- `yaru_progress_indicator.dart`

*/page*

- `yaru_page.dart`
- `yaru_section.dart`
- `yaru_tabbed_page.dart`

*/page/layout*

- `yaru_compact_layout.dart`
- `yaru_landscape_layout.dart`
- `yaru_master_detail_page.dart`
- `yaru_narrow_layout.dart`
- `yaru_wide_layout.dart`
- `yaru_portrait_layout.dart`
- `yaru_page_item_list_view.dart`
- `yaru_page_item.dart`
- `yaru_page_item_title.dart`

*/page/row*

- `yaru_row.dart`
- `yaru_single_info_row.dart`
- `yaru_slider_row.dart`
- `yaru_switch_row.dart`
- `yaru_toggle_buttons_row.dart`
- `yaru_extra_option_row.dart`
- `yaru_checkbox_row.dart`

**note:** I don't know if I should put folder names in plural.

Wdyt @Feichtmeier ?

**Comment by Feichtmeier** [comment]
Sounds good
