### ISSUE TITLE
more widgets?

### ISSUE THREAD

**Issue by valientegaston** [ubuntu/yaru_widgets.dart#184]
Hi. Great Job! I was wondering if the library contains basic widgets like textbook, combobox, multiple selected combobox, tree widgets , etc. 
Thank you.

**Comment by Feichtmeier** [comment]
Hi @valientegaston 
Great that you enjoy this lib
The idea of this lib is to be a optional topping on material widgets. 
With the yaru.dart theme (https://ubuntu.github.io/yaru.dart/#/) you get the ubuntu looks and themes for material widgets
this lib is an addition for things that are not perfect for the desktop in material or where we miss the extra look of yaru (like the spinner)
I hope this was helpful, best regards
