### ISSUE TITLE
Remove YaruAlertDialg and YaruSimpleDialog

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru_widgets.dart#203]
Eventually we should just remove those dialogs from yaruwidgets as they do not bring anything really except complexity. What one wants is the close button the rest can be done by the content inside or the dialog theme in yaru.dart

WDYT @Jupi007  ?

**Comment by Jupi007** [comment]
Yes, we just want the close button, and the correct padding. If this last can be defined in the theme, those dialog widgets can be removed.

**Comment by jpnurmi** [comment]
What kind of padding properties do we need in DialogTheme?

**Comment by Feichtmeier** [comment]
For yarudialogtitle, which is a stack of the title widget and the close button, the title padding needs to be zero
Content padding does not interfere with the close button
But I'm not sure if this is an the best way

**Comment by Jupi007** [comment]
Well the default dialog padding is `EdgeInsets.fromLTRB(0.0, 12.0, 0.0, 16.0)`, but it looks weird.
`Yaru*Dialog` was define a padding of `20` on each side, and also it removes it for the title.

**Comment by Feichtmeier** [comment]
Eventually this could be added to flutter itself?

**Comment by Jupi007** [comment]
I also think so, it would be quite simple to implement.

**Comment by jpnurmi** [comment]
Would adding DialogTheme.contentPadding and titlePadding be enough? Unfortunately, DialogTheme is one of those old theme classes that [don't follow the theme data pattern](https://github.com/flutter/flutter/pull/54642). It should have the same treatment as [ListTileTheme](https://github.com/flutter/flutter/pull/91449) recently did.

**Comment by Jupi007** [comment]
It would be enough, yes :)

**Comment by Feichtmeier** [comment]
The content padding is tricky, I would not overwrite this with the theme. Some dialogues need an even content padding, other do not
I would eventually only add the title padding

**Comment by Jupi007** [comment]
But define a better default padding wouldn't hurt, no?
You would still be able to overwrite it, indeed :)

**Comment by Feichtmeier** [comment]
Ofc, you are right :+1: 
I don't remember the default padding, is it huge?

**Comment by Jupi007** [comment]
I posted it upper ;D
It is `EdgeInsets.fromLTRB(0.0, 12.0, 0.0, 16.0)`, and honesty this looks weird (look at the fullscreen carousel padding in software app).

**Comment by Feichtmeier** [comment]
Eventually just set the default padding yaru.dart to EdgeInsets.zero ? I fear dialogues could be so diverse that not default padding fits more than 2 or 3 cases
