### ISSUE TITLE
Enhancement for arrows on image carousel

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru_widgets.dart#208]
The difference between the active and deactivated arrows in the image carousel are too subtle IMHO. I think a better solution would be if the images could just loop ♾️ or alternatively, to hide the left arrow on the first image (and right arrow for the last ofc).

For accessibility the keyboard left/right arrows should work when I click the arrows, the dots and when the image is enlarged.

![image](https://user-images.githubusercontent.com/3986894/190928425-cddee9ff-811e-43c8-8efd-09f1a1903a0e.png)

**Comment by Feichtmeier** [comment]
looping is a parameter which sometimes makes sense, sometimes not. so I would not override this with a hardocded bool honestly

**Comment by madsrh** [comment]
@Jupi007 would it be possible to a border-radius to the image? This way it would fit the other parts of the UI

**Comment by Jupi007** [comment]
@madsrh Yes it would be possible :+1: :)

**Comment by Jupi007** [comment]
@madsrh I forgotten about the keyboard thing, so reopening :)

About the border-radius, imo this should be done by the app using the carousel (aka. Software).

**Comment by madsrh** [comment]
@Jupi007 Are the (missing) keyboard bindings for fullscreen done here or in the Software app? 🤔 

Also, can the left / right arrows be present in fullscreen mode?

**Comment by Feichtmeier** [comment]
It's not missing in software you just need to click on the image :D

**Comment by madsrh** [comment]
> It's not missing in software you just need to click on the image :D

Nope, this is the latest master:

![image](https://user-images.githubusercontent.com/3986894/191975923-e8d9060e-085a-4129-997c-9d45603b3374.png)
