### ISSUE TITLE
Remove YaruSafeImage

### ISSUE THREAD

**Issue by jpnurmi** [ubuntu/yaru_widgets.dart#220]
YaruSafeImage would be better moved back to the software app.

- It assumes a network image
- It exposes only a couple of Image's properties
- It masks some of Image's default values (filter quality low -> medium, fit null -> height)
- It uses an arbitrary default size of 65

All of these are fine assumptions for an application widget but problematic, limiting, and surprising for a framework widget.

**Comment by Feichtmeier** [comment]
You are right. You want to take it?
