### ISSUE TITLE
Carousel: make animation finish correctly

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru_widgets.dart#230]
Sometimes if you change the page where the carousel sits (in software by navigating around) the carousel gets stuck somewhere in the animation and sits in an odd size and is unclickable. When the next image animated in the error is gone

![grafik](https://user-images.githubusercontent.com/15329494/193746968-31f03384-7290-4c1d-abf2-7ffe7856866e.png)

@Jupi007  any idea how to fix this? or is this rather an issue for software?
(edit: sorry jp for tagging you... your names both start with J -.-)

**Comment by Jupi007** [comment]
Hmm, I recently extracted the animation controller from the carousel.
Is software using the latest version of this lib?

**Comment by Feichtmeier** [comment]
Sorry I re-check this when we make a new release of widgets and then report back! You are prbly right!
