### ISSUE TITLE
WebExample: AppBar titles are no longer left aligned

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru_widgets.dart#256]
![Bildschirmfoto 2022-10-09 um 17 02 19](https://user-images.githubusercontent.com/15329494/194764143-7110dcc3-7283-454b-878f-7d97ca93838b.png)

**Comment by Feichtmeier** [comment]
it is web specific, linux works fine
![grafik](https://user-images.githubusercontent.com/15329494/194765565-dc36aaed-7dd4-41ee-9eb7-25b81cf5b499.png)

**Comment by Feichtmeier** [comment]
It's a Firefox thing

**Comment by Feichtmeier** [comment]
No idea what this was :question: but now it is back to normal
![grafik](https://user-images.githubusercontent.com/15329494/195037538-20a664fc-82ce-4df2-a468-e10b50ab6b59.png)

**Comment by jpnurmi** [comment]
It's strange because only apple platforms should have it centered. We could ensure with `AppBarTheme.centerTitle: false` that it's never centered, though.

**Comment by Feichtmeier** [comment]
maybe it was some funny user agent bug in firefox for this session I had? :D

**Comment by jpnurmi** [comment]
Or maybe you just got busted for developing Yaru widgets on iOS.

**Comment by jpnurmi** [comment]
Wait, I thought I was joking but the screenshot is from macOS. :grin:

**Comment by Feichtmeier** [comment]
> Wait, I thought I was being funny but the screenshot is from macOS? grin

omg! you are right! I was on that mac at that day :facepalm: 

Just in case we want yaruwidgets for the web to work on macos, too.... do we need to do something for this?

**Comment by jpnurmi** [comment]
We could enforce `AppBarTheme(centerTitle: false)` in `yaru_landscape_layout.dart` and `yaru_portrait_layout.dart` where we know for sure that centering is not the desired behavior?

**Comment by jpnurmi** [comment]
There's already a `Theme` widget for the page transitions. We could add something (ugh, so clumsy) like `appBarTheme: Theme.of(context).appBarTheme.copyWith(centerTitle: false)`?

**Comment by Feichtmeier** [comment]
or we could add this to yaru.dart?

**Comment by jpnurmi** [comment]
I'm not totally opposed but I suppose it would make sense to follow the platform conventions in general. Isn't this more like a special case where the convention doesn't fit? Actually, would it be only the left-side app bar in landscape mode that really needs centerTitle: false?

**Comment by Feichtmeier** [comment]
hm you are right this is a special case when the titles of appbars are just text I guess
as soon as something more complex like the searchbar in the flexibleSpace property in the software app happens this will not occur anymore, let's just keep everything as is or maybe I fiddle a bit with the example for the sake of not being triggered by this when I am on the mac 1 time in the month
