### ISSUE TITLE
DialogTitle: don't hide 🫥 properties with strings

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru_widgets.dart#277]
https://github.com/ubuntu/yaru_widgets.dart/blob/main/lib/src/dialogs/yaru_dialog_title.dart#L18

Again....

**Comment by jpnurmi** [comment]
wish-list:
- be able to control whether the close button is enabled/disabled (e.g. app temporarily in a busy state, must not allow closing the modal dialog)
- be able to insert a back button for a wizard type of dialog

Perhaps the API could be something similar to AppBar's?

**Comment by jpnurmi** [comment]
Could the button turn disabled or something because it stays enabled and calls pop no matter what the dialog/context/scope sets?

**Comment by Feichtmeier** [comment]
I test it, ah maybe I can work on the issue then 
Someone removed the dialog buttons from the example! :sob: :smile:

**Comment by jpnurmi** [comment]
Btw I have no clue how it's supposed to be done in Flutter but I'm hoping for a solution that lets me either disable or hide the close button instead of letting the user click it and then have to prevent it to close the dialog with a `WillPopScope`. :)

**Comment by jpnurmi** [comment]
There's `ModalRoute.canPop` but I don't understand how these things can be changed on the fly for the current route that was internally created when you called `showDialog()`... :thinking:

**Comment by Feichtmeier** [comment]
let me first move YaruAlertDialog and YaruSimpleDialog to settings
then I try to come up with a solution for the title here :)
it is really total bananas that flutter does not include this close button

**Comment by jpnurmi** [comment]
> it is really total bananas that flutter does not include this close button

For starters, I'd be happy if it allowed us to create one that just works without using custom routes. :D
