### ISSUE TITLE
Compact and MD layout master scrollareas need to work with touchpads

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru_widgets.dart#287]
Since flutter reworked how scrolling works it is now very easy to mess up touchpad scrolling
I also create this issue everytime I use a single child scrollview in software :S 

So @jpnurmi  and @Jupi007 we need to fix the two layout scrolling areas to be either the primary scrollareas (?) or with some other trick :P 
Kinda important bug :warning: 

This only happens if you use the binary outside of vscode (its a wayland / X thing)

**Comment by jpnurmi** [comment]
Is this something that Flutter 3.3 broke? How did you work it around previously?

**Comment by jpnurmi** [comment]
To reproduce from within VS Code:
```
"env": {
  "GDK_BACKEND": "wayland"
}
```

**Comment by jpnurmi** [comment]
flutter/widges/scroll_configuration.dart:
```dart
/// Device types that scrollables should accept drag gestures from by default.
const Set<PointerDeviceKind> _kTouchLikeDeviceTypes = <PointerDeviceKind>{
  PointerDeviceKind.touch,
  PointerDeviceKind.stylus,
  PointerDeviceKind.invertedStylus,
  PointerDeviceKind.trackpad,
  // The VoiceAccess sends pointer events with unknown type when scrolling
  // scrollables.
  PointerDeviceKind.unknown,
};

class ScrollBehavior {
  /// The device kinds that the scrollable will accept drag gestures from.
  ///
  /// By default only [PointerDeviceKind.touch], [PointerDeviceKind.stylus], and
  /// [PointerDeviceKind.invertedStylus] are configured to create drag gestures.
  /// Enabling this for [PointerDeviceKind.mouse] will make it difficult or
  /// impossible to select text in scrollable containers and is not recommended.
  Set<PointerDeviceKind> get dragDevices => _kTouchLikeDeviceTypes;
}
```

yaru_widgets/example/main.dart:
```dart
class TouchMouseStylusScrollBehavior extends MaterialScrollBehavior {
  @override
  Set<PointerDeviceKind> get dragDevices => {
        PointerDeviceKind.touch,
        PointerDeviceKind.mouse,
        PointerDeviceKind.stylus
      };
}
```
We seem to be missing the new `PointerDeviceKind.trackpad` value in the example.

**Comment by jpnurmi** [comment]
> I also create this issue everytime I use a single child scrollview in software :S

hmm, perhaps not the same issue because there's no scroll behavior override in software?
