### ISSUE TITLE
Move layouts outside of /pages folder

### ISSUE THREAD

**Issue by Jupi007** [ubuntu/yaru_widgets.dart#289]
I was thinking about it, and imo, it doesn't make sense to have layouts inside `/pages/layouts`, as the layout is technically surrounding pages. So I think we should move them simply in `/layouts`.

@jpnurmi @Feichtmeier If you agree, have you got any pending wip branch on these files? I don't want to create conflicts :)

**Comment by jpnurmi** [comment]
Sounds good!
