### ISSUE TITLE
Desktop Web: separator of MD page is super white in the dark theme

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru_widgets.dart#305]
Combination: dark theme + desktop + web (FF and chrome)

![grafik](https://user-images.githubusercontent.com/15329494/196217166-5f76023b-32fb-4547-b19b-ff9309f1219b.png)

Does not happen in the compact layout 🤷

**Comment by Jupi007** [comment]
Very weird, I also noticed that the separator color is changing depending on the window focus (on desktop).

**Comment by Feichtmeier** [comment]
Maybe it's related to the drawer thing 🙂
I can check maybe this evening
