### ISSUE TITLE
UbuntuLogo

### ISSUE THREAD

**Issue by jpnurmi** [ubuntu/yaru_widgets.dart#317]
Does anyone know where the [UbuntuLogo](https://pub.dev/documentation/yaru_widgets/latest/yaru_widgets/UbuntuLogo-class.html) widget might be used? Unlike the dynamically drawn and fully scalable [FlutterLogo](https://api.flutter.dev/flutter/material/FlutterLogo-class.html) widget, the UbuntuLogo widget uses a 250x250 PNG under the hood.

**Comment by jpnurmi** [comment]
I should've actually tried the widget before filing the issue. :) `UbuntuLogo` doesn't specify `yaru_widgets` package for the asset so `ubuntu_logo.png` gets looked up from app assets instead of `yaru_widgets` assets.

![image](https://user-images.githubusercontent.com/140617/197382811-5f31b176-77fb-4d24-86de-0f1893d47945.png)

```dart
import 'package:flutter/material.dart';
import 'package:yaru_widgets/yaru_widgets.dart';

void main() {
  runApp(
    const MaterialApp(
      home: Scaffold(
        body: UbuntuLogo(),
      ),
    ),
  );
}
```

**Comment by Feichtmeier** [comment]
I think this is some artefact and can be removed
While the vendor logo idea as a widget is interesting, it can be created quite easily with the yaru_icon ubuntu log for ubuntu at least. 

![grafik](https://user-images.githubusercontent.com/15329494/197383030-980ee811-e1f5-4616-9191-48dd88a7eed4.png)

https://github.com/ubuntu-flutter-community/settings/blob/279c1ff97be8dae199c143ca8162158eaae0efd5/lib/view/pages/info/info_page.dart#L76-L96

**Comment by jpnurmi** [comment]
Sounds good! Better than pulling in `flutter_svg` dependency here to be able to make the widget scalable. :)

**Comment by Feichtmeier** [comment]
We could come back to this if we have more vendor/distributor logos as yaru_icons
