### ISSUE TITLE
YaruSimpleDialog: close button should be inside the dialog frame

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru_widgets.dart#32]
![grafik](https://user-images.githubusercontent.com/15329494/147828753-cfa5612c-b3bb-4fa7-bb0a-f81629133bfe.png)

I think the close button should be inside a "regular" 4px border radius button and stay inside the dialog
or just be a smaller circle with enough padding so the position of the X stays the same but the circle does not leave the frame

WDYT @Jupi007 ?

**Comment by Jupi007** [comment]
I agree :+1: 
I'll try to fix that :)

_Sorry for the late response, some of my github notifications reached spams :(_
