### ISSUE TITLE
YaruPopupMenuButton does not exists at pub.dev version

### ISSUE THREAD

**Issue by gumbarros** [ubuntu/yaru_widgets.dart#365]
![image](https://user-images.githubusercontent.com/52143624/200656674-603a431b-465c-45b2-86bc-e788b02dfad0.png)

**Comment by jpnurmi** [comment]
You can use the pre-release version i.e. `yaru_widgets: ^2.0.0-0` until 2.0.0 final gets released.

**Comment by Feichtmeier** [comment]
or beta-1 :D

**Comment by gumbarros** [comment]
Thanks!
