### ISSUE TITLE
PopupMenu keeps changing position - default position isn't deterministic

### ISSUE THREAD

**Issue by whiskeyPeak** [ubuntu/yaru_widgets.dart#384]
I tried out the web demo for the Yaru widget library and found that the PopupButton seems to act a little weird sometimes.

For the first of the 3 buttons in the example, the popup options come out below the popup button albeit not completely. When the value is changed to option 2 or 3, the popup options are displayed over the popup button. I don't know if this is intended behaviour but I personally think the behaviour should be constant.

For the next 2 buttons, the popup options are correctly under the popup button but one is aligned to the left whilst the other is displayed to the right. Is this intended behaviour?

Video of the behaviour for each button:

https://user-images.githubusercontent.com/73116038/201811718-8f30e372-aab8-4284-a50f-82f7e8633b5f.mp4

**Comment by jpnurmi** [comment]
I'm not sure if the different choice was intentional but unlike the Material style `PopupMenuButton` that sets `PopupMenuPosition.over` by default, `YaruPopupMenuButton` specifies the position as `PopupMenuPosition.under`. Notice that this does not mean that the entire menu gets positioned under the button, but that the selected menu item is anchored right below the respective button item. Also, given that the popup menu is not a top-level window, it has to be pushed down to keep it within the window when selecting the last options.

**Comment by Feichtmeier** [comment]
not intentional, I thought under means under the button :)

**Comment by Feichtmeier** [comment]
with under and offset it works fine for the multi and checked ones
![grafik](https://user-images.githubusercontent.com/15329494/201923124-0f47dc70-5fef-4b63-96b3-f80b689182ed.png)
![grafik](https://user-images.githubusercontent.com/15329494/201923171-de1d5dca-2192-4a44-a48f-ad9004502c59.png)

but not when using normal material PopupMenuItem
![grafik](https://user-images.githubusercontent.com/15329494/201923255-5aca845f-99b5-48e1-8f8c-b669bad76909.png)

**Comment by whiskeyPeak** [comment]
I checked this again with the latest from main and the issue is still reproducible. I'll give this a look tomorrow.

**Comment by whiskeyPeak** [comment]
Did some further digging and found that getting rid of the initialValue field makes the first popupMenuButton behave like the other 2. We probably still want to set an initial value so this is most likely a bug with how flutter does its layout for the PopupMenuItem widget.

https://user-images.githubusercontent.com/73116038/202083277-901472f7-4838-4e99-b120-8d68f49a1871.mp4

**Comment by Feichtmeier** [comment]
> Did some further digging and found that getting rid of the initialValue field makes the first popupMenuButton behave like the other 2. We probably still want to set an initial value so this is most likely a bug with how flutter does its layout for the PopupMenuItem widget.
> simplescreenrecorder-2022-11-16_04.19.19.mp4

Ah! Weird! Well, yeah we can not get rid of this in general :S So I guess we either fix this in flutter (haha) or live with it?

**Comment by whiskeyPeak** [comment]
Opened up an issue at https://github.com/flutter/flutter/issues/115509#issue-1452524556 with a linked PR that fixes the general PopupMenuButton misalignment. It's still doesn't perfectly fix our issue here, but I suspect that is because a MenuItem has a slightly different height from a YaruMenuItem.




> or live with it?

It's been bugging me too much haha :sweat_smile:

**Comment by whiskeyPeak** [comment]
Flutter PR https://github.com/flutter/flutter/pull/115510
