### ISSUE TITLE
Allow switch dot to be mouse dragged

### ISSUE THREAD

**Issue by Jupi007** [ubuntu/yaru_widgets.dart#405]
I think it would be nice if the switch dot could be dragged with the mouse cursor, like in Gtk.

**Comment by Feichtmeier** [comment]
Hm sounds like a good idea, if it does not decrease performance of this widget

**Comment by Jupi007** [comment]
I don't think it will decrease performance, I will just add a drag zone which will repaint the dot position when dragging.
Simple click won't be affected by.
