### ISSUE TITLE
Rename `YaruCompactLayout`?

### ISSUE THREAD

**Issue by jpnurmi** [ubuntu/yaru_widgets.dart#416]
While we still have a chance to land breaking changes before 2.0, it would be nice if `YaruCompactLayout` had a name that:
- sounds like a counterpart to `YaruMasterDetailPage`
- sounds like a natural use-case for `YaruPageController`
- hints that it's based on `YaruNavigationRail` (and possibly `YaruBottomNavigationBar`)
- doesn't sound like an internal helper class like `YaruMasterDetailPage`'s `YaruPortraitLayout` and `YaruLandscapeLayout`

_Originally posted by @jpnurmi in https://github.com/ubuntu/yaru_widgets.dart/issues/414#issuecomment-1326684850_

> I wish `YaruCompactLayout` would be named something like `YaruNavigationPage` to be consistent with `YaruMasterDetailPage` and `YaruNavigationRail` but it would break the software app once again... :thinking:

_Originally posted by @jpnurmi in https://github.com/ubuntu/yaru_widgets.dart/issues/284#issuecomment-1275801935_

> - `YaruNavigation`Page
> - `YaruNavigation`(Page)Theme
> - `YaruNavigation`Rail
> - `YaruNavigation`(Rail)Item
> - `YaruNavigation`Bar
> - ...?

**Comment by Jupi007** [comment]
Personally, I think that `YaruNavigationPage` sounds good.
But what is the problem with the software app?

**Comment by jpnurmi** [comment]
I didn't buy my own proposal earlier because it didn't feel like a big enough improvement to justify the break. I decided to bring it up again now that we have `YaruPageController` in the pipeline.

Also, I'm starting to feel embarrassed for breaking all the apps again and again but if Frederik says it's ok... :see_no_evil:
