### ISSUE TITLE
YaruNavigationPage initialIndex is not forwarded to NavigationRail

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru_widgets.dart#456]
I know we got the controller thing now. But even if this might be an artefact or not but the initialindex is always 0

CC @d-loose @Jupi007 

I need this for https://github.com/ubuntu-flutter-community/software/pull/625

**Comment by Feichtmeier** [comment]
nvm it works with
                YaruPageController(length: pageItems.length, initialIndex: 3),

**Comment by Jupi007** [comment]
Nice that it works finally :)
And sorry, because I have forgotten to look at.

**Comment by Feichtmeier** [comment]
the initialindex can be removed with the controller

**Comment by Jupi007** [comment]
Just had a quick look, I think we miss to pass the `initialIndex` to the default/fallback controller:

https://github.com/ubuntu/yaru_widgets.dart/blob/6928eaf1d6ab3d499a864b5f7605dc7004b30ef2/lib/src/layouts/yaru_navigation_page.dart#L94-L95

Should be:

```dart
_pageController = widget.controller ??
  YaruPageController(
     length: widget.length!,
     initialIndex: widget.initialIndex!,
  );
```

**Comment by Feichtmeier** [comment]
it works if I do neithe ruse length nor initialIndex directly but only pass a controller which itself has length and initialindex
Maybe we should then just remove the length and initialindex as arguments and instead only use the controller?

**Comment by Jupi007** [comment]
Well, have these argument is really simpler, because pass a controller mean you need to store and dispose it.
