### ISSUE TITLE
YaruPopupMenuButton width/layout

### ISSUE THREAD

**Issue by jpnurmi** [ubuntu/yaru_widgets.dart#459]
When `YaruPopupMenuButton` is expanded in width, the dropdown indicator could be aligned to the right.

![image](https://user-images.githubusercontent.com/140617/207542192-826d2e9d-1024-407e-aee7-bc786bec63c7.png)

Perhaps the menu could also expand to the width of the button when it's wide like this?

**Comment by jpnurmi** [comment]
P.S. This was just an experiment to see what happens if we replace this kind of Material-style dropdown with the Yaru popup menu button:

![image](https://user-images.githubusercontent.com/140617/207542389-0c1f66ea-1091-4e7e-a64c-d98f10b5d7e5.png)
![image](https://user-images.githubusercontent.com/140617/207542406-398463bf-e12c-4ca9-83e6-4c35316be48b.png)

**Comment by Feichtmeier** [comment]
Fixed with https://github.com/ubuntu/yaru_widgets.dart/pull/471
