### ISSUE TITLE
Navi rail: remove extra space

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru_widgets.dart#465]
![grafik](https://user-images.githubusercontent.com/15329494/210226420-7c568186-8a0d-41f7-8e68-1ad6d78371b7.png)

There seems to be extra space above the first element here

**Comment by Jupi007** [comment]
You don't remember? ;D
I added a little padding to align the first item to the search entry of the software app: https://github.com/ubuntu/yaru_widgets.dart/pull/201#issuecomment-1269690431

**Comment by Feichtmeier** [comment]
Yes sorry - I miss the old software header design a lot 😢 
I guess for multiple filters it makes mroe sense to have them under the input.
Anyways, now it shouldn't matter that much anymore I think and the gap always jumped into my sight 😄
