### ISSUE TITLE
Question about how to change YaruRadio color?

### ISSUE THREAD

**Issue by HePingLaoSan** [ubuntu/yaru_widgets.dart#477]
Can somebody tell me how to change YaruRadio color? when launch in my computer, my color which is blue is different from demo which is orange.

**Comment by Feichtmeier** [comment]
hi @HePingLaoSan which distribution are you using? and if you use normal ubuntu, did you maybe change your theme to blue? yaru.dart detects the system theme on vanilla ubuntu and adapts

**Comment by jpnurmi** [comment]
One way to change the color on any platform is to force a specific [variant](https://pub.dev/documentation/yaru/latest/yaru/YaruVariant.html) of the Yaru theme:

```dart
import 'package:flutter/material.dart';
import 'package:yaru/yaru.dart';
import 'package:yaru_widgets/yaru_widgets.dart';

void main() {
  runApp(
    YaruTheme(
      data: const YaruThemeData(
        variant: YaruVariant.purple, // <==
      ),
      builder: (context, yaru, child) {
        return MaterialApp(
          theme: yaru.theme,
          darkTheme: yaru.darkTheme,
          home: Scaffold(
            body: Center(
              child: YaruRadio(
                value: true,
                groupValue: true,
                onChanged: (value) {},
              ),
            ),
          ),
        );
      },
    ),
  );
}
```
![image](https://user-images.githubusercontent.com/140617/211498930-1e602be9-e88f-4c04-bdd0-4f5d98018eec.png)

**Comment by Jupi007** [comment]
I also plan to add some override properties soon, so we can locally change the colour of a specific control.
