### ISSUE TITLE
Title bar corners

### ISSUE THREAD

**Issue by jpnurmi** [ubuntu/yaru_widgets.dart#481]
![image](https://user-images.githubusercontent.com/140617/211612658-5e89681d-664d-43ed-9cfd-af9a7df1e23b.png)

**Comment by jpnurmi** [comment]
Now I remember the reason why it used to be fully transparent by default... :D

**Comment by jpnurmi** [comment]
Maybe we could specify the expected shape with rounded top corners for `YaruDialogTitleBar`?

**Comment by Feichtmeier** [comment]
So the reason is that the YaruTitleBar has the wrong border radius?

**Comment by jpnurmi** [comment]
`YaruTitleBar` creates an `AppBar` that doesn't have rounded corners by default. We used to make it transparent before to avoid this issue in dialogs.

**Comment by jpnurmi** [comment]
We didn't know where the generic `YaruTitleBar` was used so it didn't make sense to force rounded corners. Now that we have a separate `YaruDialogTitleBar`, we can assume that the latter is used in dialogs and therefore needs rounded corners... :)
