### ISSUE TITLE
AppBar vs. YaruTitleBar height

### ISSUE THREAD

**Issue by jpnurmi** [ubuntu/yaru_widgets.dart#502]
[yaru.dart/constants.dart](https://github.com/ubuntu/yaru.dart/blob/3cc3b6639564a63ace25beaf102ce00e993f9aae/lib/src/themes/constants.dart#L7)
```dart
const kAppBarHeight = 48.0;
```

vs.

[yaru_widgets.dart/constants.dart](https://github.com/ubuntu/yaru_widgets.dart/blob/main/lib/src/constants.dart#L5)
```dart
const kYaruTitleBarHeight = 47.0;
``` 

`AppBarTheme.toolbarHeight` has been traditionally used in many places. [`YaruDetailPage`](https://github.com/ubuntu/yaru_widgets.dart/pull/501) is one of the victims and even though it was easy to fix, similar off-by-one issues could appear in apps.

![image](https://user-images.githubusercontent.com/140617/212023399-2f296428-ca23-4af1-949f-6131475892d1.png)

**Comment by Feichtmeier** [comment]
then let's go with 47, it's the only way to have the yaruwindowtitlebar with a border to have the same height as gtkheaderbar
