### ISSUE TITLE
Delay when pressing the minimise, maximise and close buttons.

### ISSUE THREAD

**Issue by whiskeyPeak** [ubuntu/yaru_widgets.dart#516]
This is kinda hard to show on video, but there is a small delay after pressing those buttons before the window is finely minimised, maximised or closed.

I think this may be because the onDoubleTap argument is used, so Flutter has to wait for a given time to check for a 2nd tap event to occur.

For example, when double pressing the minimise button, the window will maximise. I checked this behaviour with other apps and they minimise/maximise/close as soon as the first tapDown event is completed.

Edit:

This also applies to the tab buttons in the updates page of the software store but doesn't apply to the text-field in the explore and installed pages.

**Comment by jpnurmi** [comment]
Hah, how did I not notice that! This is indeed due to how gesture negotiation works in Flutter. A single tap gesture can only declare itself as a winner after waiting for 300ms when there's a double-tap gesture in the same arena... :(

**Comment by Feichtmeier** [comment]
It's not perfect but I don't think this should be a show-stopper for CSD

**Comment by whiskeyPeak** [comment]
We could replace the gesture detector widget with a Listener widget for those specific buttons.

```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: GestureDetector(
        onTap: () {
          print("tap from 1st gesture detector");
        },
        onDoubleTap: () {
          print("double tap from 1st gesture detector");
        },
        child: Container(
          width: 500,
          height: 500,
          color: Colors.grey,
          child: Center(
            child: Listener(
              onPointerUp: (PointerUpEvent event) {
                print("tap from the listener");
              },
              child: const Text("Hello there"),
            ),
          ),
        ),
      ),
    );
  }
}

```
Definitely feels faster imo.

**Comment by jpnurmi** [comment]
This affects any widgets users may put in the title bar. Also, this makes me realize that the behavior with movable tabs feeling a bit off in the Workshops app might have something to do with this too. Thanks for bringing it up! 👍

A passive double-click handler would be optimal because we are only interested in double-clicks that come through "unobstructed" without negotiation with single-click handlers.
