### ISSUE TITLE
Window control spacing

### ISSUE THREAD

**Issue by jpnurmi** [ubuntu/yaru_widgets.dart#523]
GtkHeaderBar and YaruTitleBar have a different spacing (observed 22.10).

![image](https://user-images.githubusercontent.com/140617/212493340-96e56546-1e7f-4b55-b0a5-db28e1c64afb.png)

```dart
import 'package:flutter/material.dart';
import 'package:yaru/yaru.dart';
import 'package:yaru_widgets/yaru_widgets.dart';

Future<void> main() async {
  runApp(
    MaterialApp(
      theme: yaruLight,
      darkTheme: yaruDark,
      debugShowCheckedModeBanner: false,
      home: const Scaffold(
        appBar: YaruWindowTitleBar(
          title: Text('YaruWindowTitleBar'),
        ),
      ),
    ),
  );
}
```

**Comment by Jupi007** [comment]
Do you mean the window controls?
If yes, it is normal, the headerbar is a gtk3 one, but we use the same spacing as libadwaita, which is smaller.

**Comment by jpnurmi** [comment]
Ahh, thanks! I didn't realize the difference between gtk3 and libadwaita, sorry! Never mind :)

**Comment by Jupi007** [comment]
No problem. To be honest, I had the same thought a few day ago 😅
Then I remembered libadwaita difference!
