### ISSUE TITLE
PopupMenuButton doesn't open if another menu is already open

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru_widgets.dart#548]
When I open the menu _Multi Select_, and then click the _option 1_, menu then it closes _Multi Select_.
I would have expected it to open _option 1_ AND close  _Multi Select_ without the additional mouse click.

I hope this makes sense (problems with screen recorder) 🙄 

![image](https://user-images.githubusercontent.com/3986894/213548933-453b02b1-993b-41dd-9bec-479fe9ced0ff.png)

**Comment by Feichtmeier** [comment]
hehe
look on your screenshot :) :eye:

**Comment by madsrh** [comment]
I mean option 1 as in the drop-down, not the checkbox 😅

**Comment by Feichtmeier** [comment]
I am sorry but i dont undestand what youmean

**Comment by madsrh** [comment]
OOOhhhhhh, no! I'm totally mistaken here 💩 What I wanted was to be able to open a second menu while the first one is open. It just doesn't work like that in Linux, Windows or OSX so... 🙄 
> I am sorry but i dont undestand what you mean

Not my best description, but you get maximum points for trying 🥇 

### Sorry for the noise!!!

**Comment by Feichtmeier** [comment]
NP

![](https://media.giphy.com/media/TNqMlgTuv5jJ6/giphy.gif)
