### ISSUE TITLE
YaruTile trailing has wrong text color

### ISSUE THREAD

**Issue by Jupi007** [ubuntu/yaru_widgets.dart#559]
**Current:**

![Capture d’écran du 2023-01-22 21-47-29](https://user-images.githubusercontent.com/36476595/213939597-074a1e9b-6662-47d2-a5ee-5141cf2524f5.png)

**Expected:**

![Capture d’écran du 2023-01-22 21-47-19](https://user-images.githubusercontent.com/36476595/213939614-db5d84af-5c37-4228-aa58-4c468af30699.png)

Related to https://github.com/ubuntu-flutter-community/software/issues/849

**Comment by madsrh** [comment]
Sorry, I was too slow 😄 
Thank you!
