### ISSUE TITLE
Transparent title bar when window inactive

### ISSUE THREAD

**Issue by jpnurmi** [ubuntu/yaru_widgets.dart#577]
The background of an inactive title bar is transparent, which makes it leak stuff through. It could be a banner like below, or it could be scrollable content. Could we make it opaque instead?

| Active | Inactive |
|---|---|
| ![image](https://user-images.githubusercontent.com/140617/216637097-0f70a8dc-4900-49d1-a0c8-5e8f6c2f1603.png) | ![image](https://user-images.githubusercontent.com/140617/216636988-516fe3fe-5eeb-4ab1-83bc-3c44415a8604.png) |

**Comment by jpnurmi** [comment]
It's not hard to clip the content but performance-wise it's better to avoid clipping whenever possible. In this case, you wouldn't have to if the title bar was opaque.

We allow customizing the background color so apps can set it to transparent if they want the content below to see through, but it probably should not be the default because it's very uncommon that there's anything interesting behind a window title bar. :)

**Comment by Feichtmeier** [comment]
Yes opaque sounds good! I suppose Theme.of(context).colorScheme.background should be correct

**Comment by Jupi007** [comment]
> Yes opaque sounds good! I suppose Theme.of(context).colorScheme.background should be correct

Yes, this is the correct backdrop color for the titlebar 👍
