### ISSUE TITLE
Page indicator

### ISSUE THREAD

**Issue by jpnurmi** [ubuntu/yaru_widgets.dart#582]
Could we have this as a standalone widget? It would be useful for non-carousel page views and wizards etc. 

![image](https://user-images.githubusercontent.com/140617/216781835-4de3e3be-131e-4d89-830c-cf2991f0effb.png)

**Comment by Jupi007** [comment]
Ofc, this is a good idea 👍

I was also thinking about allow a customisation of the carousel place indicator, by decouple it from the carousel itself.
