### ISSUE TITLE
Project structure

### ISSUE THREAD

**Issue by jpnurmi** [ubuntu/yaru_widgets.dart#585]
_Originally posted by @jpnurmi in https://github.com/ubuntu/yaru_widgets.dart/issues/583#issuecomment-1417147131_

> I also don't know why YaruBanner is in utils/, YaruTile in pages/, and YaruWindow in controls/... :man_shrugging: Maybe we can just flatten the tree?

**Comment by jpnurmi** [comment]
Flatting is probably not the right solution either. We should rather have layers and feature subdirs where needed.

**Comment by Feichtmeier** [comment]
maybe just rename the dir "pages" to "boxes" or "containers" or "shelfs"
