### ISSUE TITLE
uses-material-design

### ISSUE THREAD

**Issue by jpnurmi** [ubuntu/yaru_widgets.dart#607]
Why does `yaru_widgets` set `uses-material-design: true` in its pubspec? Is it not supposed to be set by applications?

I keep getting this annoying warning whenever I run tests for the `ubuntu-desktop-installer/packages/ubuntu_wizard` package:
```
ubuntu-desktop-installer/packages/ubuntu_wizard (main)$ flutter test
package:yaru_widgets has `uses-material-design: true` set but the primary pubspec contains `uses-material-design: false`. If the application needs material icons, then
`uses-material-design`  must be set to true.
00:04 +81: All tests passed!         
```

**Comment by Feichtmeier** [comment]
I have seriously no idea why this is set =) maybe in the migration phase this was needed?

**Comment by jpnurmi** [comment]
Ok, let's kill it with joy and then we'll wait and see if anything breaks :)
