### ISSUE TITLE
YaruWindowTitleBar color changes on drag

### ISSUE THREAD

**Issue by whiskeyPeak** [ubuntu/yaru_widgets.dart#615]
The behaviour seems a little awkward to me? It seems that when the window is dragged, the YaruWindowTitleBar reverts to "unfocused" colours.
We should probably also animated the switch in colours from focused to unfocused as well.

[Screencast from 2023-02-11 20-37-29.webm](https://user-images.githubusercontent.com/73116038/218280133-06d425d8-21ac-474f-b33c-87e42fb445d8.webm)

**Comment by jpnurmi** [comment]
I'm not sure what's up with the background color but the state will get fixed when we switch from window_manager to yaru_window.dart.

**Comment by whiskeyPeak** [comment]
> I'm not sure what's up with the background color but the state will get fixed when we switch from window_manager to yaru_window.dart.

Ah nice!

I tested this a bit further and now got to a point where i have 2 different application running the same code (and having applied flutter clean) both showing different behaviour.

[Screencast from 2023-02-11 23-11-24.webm](https://user-images.githubusercontent.com/73116038/218285070-25621797-79a4-41c6-821b-2a03ed4cb749.webm)

O_o

**Comment by jpnurmi** [comment]
The state should be fixed in 2.1.0.

- https://github.com/ubuntu/yaru_widgets.dart/pull/618

Why is the background color so bright when the window is inactive, though?

**Comment by Jupi007** [comment]
This is fixed in latest version, can we close?

[Capture vidéo du 2023-02-25 16-16-25.webm](https://user-images.githubusercontent.com/36476595/221364848-63b1c012-d4c5-47e4-880d-a3bf83051925.webm)
