### ISSUE TITLE
Drop YaruSwitch.checkmarkColor earlier

### ISSUE THREAD

**Issue by Jupi007** [ubuntu/yaru_widgets.dart#627]
@jpnurmi I first set the removal of this property to the 3.0 release.
But this may be in a very long time (remember 2.0-beta 😝), and I was wondering if we shouldn't update the comment and drop this in a future 2.2 release?

https://github.com/ubuntu/yaru_widgets.dart/blob/d61aa567320fdc3b5af78101e740e0ab7d415dea/lib/src/widgets/yaru_switch.dart#L94-L98

**Comment by jpnurmi** [comment]
Sounds good to me 👍
