### ISSUE TITLE
YaruPageIndicatorTheme

### ISSUE THREAD

**Issue by jpnurmi** [ubuntu/yaru_widgets.dart#631]
We would like to customize `YaruPageIndicator` to look like this in the [installer](https://github.com/canonical/ubuntu-desktop-installer/pull/1445#issuecomment-1441899274):

![image](https://user-images.githubusercontent.com/140617/221228938-78f5c7fa-9976-4ad0-9bdb-d62a6f508c15.png)

Perhaps we could expose some `BoxDecoration` properties such as shape, color, and border for the different states (current vs. past vs. future) via `YaruPageIndicatorTheme(Data)`?

**Comment by Jupi007** [comment]
That's a really good idea!
Have you already got some work in progress, or can I take it?

**Comment by jpnurmi** [comment]
Sure, feel free to. :) I didn't start anything yet besides browsing around Flutter to see what kind of decoration-related properties they usually have in the theming APIs. Shape and border etc. seem to be quite common. :)

**Comment by Jupi007** [comment]
@jpnurmi I'd like to introduce some breaking changes, related to the way of compute and expose dot spacing and size. But it's not something which justify a new minor version right away.
So what do you think of have a separate branch like `2.2-dev` where we could work on some new breaking features.
And when we are satisfied of the result, this branch could be merged into `main`.

This would allow to us some work flexibilities.

If we go in that way, I could introduce the page indicator theme in `main` right now, but in addition to that, I could go further in the dev branch.

**Comment by jpnurmi** [comment]
@Jupi007 sounds like a good idea! don't stress too much about some layout breaks. it's a brand-new widget so not widely used yet :)

**Comment by Jupi007** [comment]
Cool, thanks :)

It is not that I'm really worried about it, but more that if we need to bump the minor version for each change like that, it will become a little bit a mess of version. And also, I like to make things clean 😉
