### ISSUE TITLE
YaruImageTile: replace path with an image widget

### ISSUE THREAD

**Issue by jpnurmi** [ubuntu/yaru_widgets.dart#68]
A `String path` property is problematic because it doesn't let apps specify the desired type of image widget. For example, the Ubuntu Desktop Installer needs to pass a `FlavorImage` widget for looking up flavor theme thumbnails in canonical/ubuntu-desktop-installer#656. Please consider changing the property to a usual `Widget child` as it is in 95% of cases in Flutter. This would give apps full control over the image.

**Comment by Feichtmeier** [comment]
@jpnurmi oh, that is indeed problematic

I tried to make the library web compatible by populating the image with

https://github.com/ubuntu/yaru_widgets.dart/blob/ffd30e150e2758893462181c1392cda08ce7ac45/lib/src/yaru_image_tile.dart#L62-L68

depending on the platform. 
Any idea how we could keep web compatibility? Or do you basically want to remove the whole image part from YaruImageTile and functioally reduce it to a "YaruSelectableTile" ?

**Comment by jpnurmi** [comment]
> I tried to make the library web compatible by populating the image with

It's better to leave such decisions to apps because there's no way to know what the app needs. For example, even if Image.file() might work for assets on desktop platforms (because assets happen to be files located in a matching directory), it won't work on mobile where assets are not ordinary files on the file system.

Flutter's philosophy is to allow freely composing widgets and to avoid assuming/restricting the type of children unless absolutely necessary. For example, even if IconButton.icon is normally an Icon, it allows any Widget because you might want to e.g. wrap the icon with another widget, or even use something else than Icon.

> reduce it to a "YaruSelectableTile" ?

That's an option if there's nothing left specifically for images. Is there anything

**Comment by Feichtmeier** [comment]
Alright - will do. Only need to find a solution for the BoxFit.fill, because this is what makes the image work almost everywhere

**Comment by jpnurmi** [comment]
Could it be something documented in the class description together with an example snippet, as a recommended way to use the widget?

**Comment by Feichtmeier** [comment]
I've decided that adding two lines of code for an image somewhere is not really a problem and just went with your suggestion, without adding a specified example because I found the YaruSelectableContainer to be quiet usefull for shapes and text in the example :)
