### ISSUE TITLE
add the missing optional icon parameters

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru_widgets.dart#739]
@Jupi007 @jpnurmi 

IMO we should remove the dependency to yaru icons
The amount of places where we use them is so low that I don't see why we just shouldn't add a required IconData or Icon parameter to these widgets:

![grafik](https://github.com/ubuntu/yaru_widgets.dart/assets/15329494/8726d56d-fd71-4635-abcd-142791861794)

Apart from making the dependency management easier across our apps and libs this would also make yaru widgets to be more opened to be used for example with adwaita icons or material icons

**Comment by Jupi007** [comment]
@jpnurmi could it be a good idea to have a Theme class dedicated to the icons?
I mean that, this way, we only need to define the desired set of icons once, an not every time we use a yaru widget in the tree.

**Comment by jpnurmi** [comment]
How often is there a new breaking major version of yaru_widgets?

Dependabot runs daily. Next time, it will automatically open a PR to bump the version. Once you merge that, release-please will automatically create or update a release PR. Once you merge and publish that, you have compatible versions available.

It would be nice to have all icons exposed as widget and theme properties but personally, I'd still keep the defaults. Asking users to set the defaults will sort of push the problem to the users, and result in inconsistent looks if/when they don't bother customizing the icons...

**Comment by jpnurmi** [comment]
P.S. It's also possible to manually trigger Dependabot but the button is unfortunately buried pretty deep

_Insights_ -> _Dependency graph_ -> _Dependabot_ -> _Last checked xxx_ -> _Check for updates_

**Comment by jpnurmi** [comment]
What about relaxing the version constraint?

Before:
```yaml
yaru_icons: ^1.0.0 # same as '>=1.0.0 <2.0.0'
```
After:
```yaml
yaru_icons: '>=1.0.0'
```

**Comment by Jupi007** [comment]
> What about relaxing the version constraint?

As the major version only concerns the animated icons which aren't used in this repository, it is imo a good idea :+1:

**Comment by Feichtmeier** [comment]
> What about relaxing the version constraint?
> 
> Before:
> ```yaml
> yaru_icons: ^1.0.0 # same as '>=1.0.0 <2.0.0'
> ```
> After:
> ```yaml
> yaru_icons: '>=1.0.0'
> ```

This is a solution for soft changes indeed

But what about this problem

> Apart from making the dependency management easier across our apps and libs this would also make yaru widgets to be more opened to be used for example with adwaita icons or material icons

?

**Comment by Feichtmeier** [comment]
I'll just start with adding optional icon parameters where we've forgotten it
