### ISSUE TITLE
relax yaru_icons.dart version constraint

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru_widgets.dart#742]
What about relaxing the version constraint?

Before:
```yaml
yaru_icons: ^1.0.0 # same as '>=1.0.0 <2.0.0'
```
After:
```yaml
yaru_icons: '>=1.0.0'
```

_Originally posted by @jpnurmi in https://github.com/ubuntu/yaru_widgets.dart/issues/739#issuecomment-1656714020_

**Comment by jpnurmi** [comment]
- https://github.com/ubuntu/yaru_widgets.dart/pull/747
