### ISSUE TITLE
YaruNavigationRailItem: add an option to make selection span icon + label

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru_widgets.dart#753]
@Jupi007 would be cool to have an option to make the labelledExtended version look a bit like the master tiles
What would be the best thing here in your opinion? make mastertile work here too or add an option to navi rail items?

![grafik](https://github.com/ubuntu/yaru_widgets.dart/assets/15329494/c4cc8658-38be-4983-87d3-dc8e9fb8602f)
![grafik](https://github.com/ubuntu/yaru_widgets.dart/assets/15329494/52131313-bf92-476e-81c1-78b761936513)

**Comment by Jupi007** [comment]
I have something in mind since a long time: drop the yaru nav rail, instead use the landscape layout alone, and provide various tiles look.
This would be way more flexible, simpler, and would avoid duplicated stuff across layouts that are basically the same.

About your question itself, for now it would be simpler to add an option, instead of let the master tile work with the navi rail.

**Comment by Jupi007** [comment]
I'm working on :)

**Comment by Jupi007** [comment]
@Feichtmeier What do you think of this:

| Large | Medium | Small |
| --- | --- | --- |
| ![Capture d’écran du 2023-08-10 23-56-04](https://github.com/ubuntu/yaru_widgets.dart/assets/36476595/0acffb6b-88b1-4c9f-a346-34f157c24de2) | ![Capture d’écran du 2023-08-10 23-58-29](https://github.com/ubuntu/yaru_widgets.dart/assets/36476595/3db4df01-ce4c-46b4-90d3-f142a9425fb3) | ![Capture d’écran du 2023-08-10 23-58-51](https://github.com/ubuntu/yaru_widgets.dart/assets/36476595/ec8b9809-c486-4aed-b90f-a79909a760a0) |

**Comment by Feichtmeier** [comment]
This is very nice! Eventually a bit more padding but this is nit picking xD

**Comment by Jupi007** [comment]
> Eventually a bit more padding

In all size state?

In fact I tried to keep the same compact sizing, so in medium state there's not that available place.

**Comment by Jupi007** [comment]
Is it better like this?

| Large | Medium | Small |
| --- | --- | --- |
| ![Capture d’écran du 2023-08-11 11-44-22](https://github.com/ubuntu/yaru_widgets.dart/assets/36476595/6c38a27e-bcd4-407c-abc7-380040aa3917) | ![Capture d’écran du 2023-08-11 11-43-51](https://github.com/ubuntu/yaru_widgets.dart/assets/36476595/b56e7bbe-cae9-4f07-9734-1ee71f962a3d) | ![Capture d’écran du 2023-08-11 11-43-46](https://github.com/ubuntu/yaru_widgets.dart/assets/36476595/bd6bef8d-a8f1-4199-b6c5-a8cf5840029b) |

**Comment by Feichtmeier** [comment]
> Is it better like this?
> 
> | Large | Medium | Small |
> | --- | --- | --- |
> | ![Capture d’écran du 2023-08-11 11-44-22](https://github.com/ubuntu/yaru_widgets.dart/assets/36476595/6c38a27e-bcd4-407c-abc7-380040aa3917) | ![Capture d’écran du 2023-08-11 11-43-51](https://github.com/ubuntu/yaru_widgets.dart/assets/36476595/b56e7bbe-cae9-4f07-9734-1ee71f962a3d) | ![Capture d’écran du 2023-08-11 11-43-46](https://github.com/ubuntu/yaru_widgets.dart/assets/36476595/bd6bef8d-a8f1-4199-b6c5-a8cf5840029b) |
> 

Yes I think it looks better :)

Could you also add a borderRadius property to play around with?
