### ISSUE TITLE
[Suggestion] Publish example web project so that developers can easily browse through widgets

### ISSUE THREAD

**Issue by defuncart** [ubuntu/yaru_widgets.dart#76]
As the example app already targets web, it could be published, for instance, as a GitHub page, similar to what [macos_ui](https://groovinchip.github.io/macos_ui/#/) and [fluent_ui](https://bdlukaa.github.io/fluent_ui/) do.

This would benefit developers who don't code on ubuntu but are targeting ubuntu as a desktop platform.

**Comment by Feichtmeier** [comment]
Hi @defuncart 
Thanks for the nice suggestion! Very good idea
